version: "3"
services:
        api:
                build:
                        context: './api'
                environment:
                        - NODE_ENV=development
                ports:
                        - 3000:3000
                links:
                        - mongo
                command: npm start
        mongo:
                container_name: mongo
                image: mongo
                ports:
                - 27017:27017
